### ISSUE TITLE
Conversational AI Swift UI Demo issue

### ISSUE THREAD

**Issue by seyhunak** [elevenlabs/elevenlabs-examples#105]
Hello

Checked out the example and tested with my existing AgentId on the ConversationalAIExampleView and ran into Simulator, during recording getting following error and not submitting voice to the ElevenLabs Agent,

Any advise?

```
AddInstanceForFactory: No factory registered for id <CFUUID 0x600000256020> F8BB1C28-BAE8-11D6-9C31-00039315CD46
Failed to send WebSocket message: cancelled
Error: Failed to send WebSocket message
WebSocket error: The operation couldn’t be completed. Socket is not connected
Error: WebSocket error

```
Env: Using Xcode 16.1 - Swift UI

**Comment by louisjoecodes** [comment]
Checking!

**Comment by vinayshankardubey** [comment]
Same Here not working with me also..

**Comment by louisjoecodes** [comment]
Are you using the latest SDK version?

https://github.com/elevenlabs/ElevenLabsSwift

**Comment by louisjoecodes** [comment]
This example is planned to be updated tomorrow. Apologies for the delay folks. Functionality is ever-evolving with conversation ai, especially on launch week.

**Comment by seyhunak** [comment]
> This example is planned to be updated tomorrow. Apologies for the delay folks. Functionality is ever-evolving with conversation ai, especially on launch week.

Thanks @louisjoecodes

**Comment by lofthoue83** [comment]
We also have same issues. So that would be really helpful if we get an update before the weekend that we can still start our agent. :+1: :shipit:

**Comment by louisjoecodes** [comment]
I have updated the Swift Conversational AI example to point to the latest [SDK version](https://github.com/elevenlabs/ElevenLabsSwift)

This should resolve the issue above.

Notes:
- Please replace the agent ID with an agent that is public. If using private agents please follow [this](https://elevenlabs.io/docs/conversational-ai/libraries/conversational-ai-sdk-swift) guide.
```
        Agent(
            id: "<insert-agent-url-here>",
            name: "Matilda",
            description: "Math tutor"
        ),
```

Please feel free to open a new issue or ping me directly `louis@elevenlabs.io` with any new issues.

**Comment by seyhunak** [comment]
Thanks @louisjoecodes 

Fetched and pulled with your changes in main branch and tested. 

This time, my public AgentID initialized properly, but getting often web socket errors during testing using Simulator and if Elevenlabs Agent responses, sound stucks during Agent speaking, it seems due to web socket connection.

Passed my agent ID as instructed.

  Agent(
            id: "<insert-agent-url-here>",
            name: "Matilda",
            description: "Math tutor"
        ),

Here you may see quick conversation log printed on Xcode console, 

```
iOSSimulatorAudioDevice-29642-1: Abandoning I/O cycle because reconfig pending
Hello, I am Math tutor of Matilda. How can I help you to learn Math today?
Error: Unknown message type
Hello, I am Math tutor of Matilda. How can I help you to learn Math today?
Hello! I'm excited to help you learn Math.  What are you hoping to work on today? Do you have any specific challenges youd like to focus on? 
Error: Unknown message type
Hello, I'm excited to help...
It's great to hear you're enthusiastic about learning Math!  What area would you like to focus on today?  Are you interested in improving your skills or something else?  
Let me know what you'd like to work on. 
Error: Unknown message type
to hear your...
to hear you're excited to learn Math!  What can I help you with today?  Do you have any specific areas?
Error: Unknown message type
WebSocket error: The operation couldn’t be completed. Socket is not connected
Error: WebSocket error

```

**Comment by lofthoue83** [comment]
Awesome! It is working!!! Thank you @louisjoecodes !

**Comment by seyhunak** [comment]
Thanks @louisjoecodes  

Figured out the issue, after the refreshing Xcode cache and re-building fixed the issue.
