### ISSUE TITLE
Audio Native - get error

### ISSUE THREAD

**Issue by arashberlin** [elevenlabs/elevenlabs-examples#20]
Hi,

I've been attempting to enable the Audio Native feature by following your provided examples. However, I've encountered some issues in getting it operational.

I've ensured that the URLs are correctly set up in the Allowed URLs section.

Despite this, I'm facing the following errors: "Cannot read properties of undefined (reading 'message')", which seems to be a JavaScript error related to accessing a property of an undefined object.

Additionally, there's a 404 error when making a POST request to https://api.elevenlabs.io/v1/audio-native/..../convert, indicating that the server can't find the requested resource.

Could you provide guidance or a solution to resolve these errors?

Thank you for your assistance.

![image](https://github.com/elevenlabs/elevenlabs-examples/assets/12381397/86ab46c6-4eb0-458c-bab7-0e6af153bd80)
<img width="1286" alt="image" src="https://github.com/elevenlabs/elevenlabs-examples/assets/12381397/ba53ecaf-9ea0-4462-b40e-227f809e8cd8">

![image](https://github.com/elevenlabs/elevenlabs-examples/assets/12381397/793ffd4f-a9db-4169-8452-cf345b871df8)

![image](https://github.com/elevenlabs/elevenlabs-examples/assets/12381397/a3861774-9007-47a3-b034-625907db7f8f)

![image](https://github.com/elevenlabs/elevenlabs-examples/assets/12381397/a93b110c-4753-4a0d-888b-4a45c7402a12)

![image](https://github.com/elevenlabs/elevenlabs-examples/assets/12381397/a26c464c-6845-44ac-8c40-1ca963b62fae)

**Comment by Mateusz-Kopec** [comment]
Hi @arashberlin, thank you for reaching out! 

Our article retriever needs to have access to the website where the AudioNative player is hosted. So if you are testing with localhost, it cannot get access to the website and that's where error is coming from. I'll look into making error message correct though, thanks for pointing that out.

There are few ways you can test the player locally:

1. Use ngrok, localtunnel or similar service to expose the localhost to the world and then allowlist the exposed url in Elevenlabs.
2. Use projects and embed the existing project - https://elevenlabs.io/docs/audio-native/overview#method-2-embed-audio-from-an-existing-project
3. Use API to integrate - https://elevenlabs.io/docs/audio-native/overview#method-3-embed-audio-from-content-using-our-api

Let me know if that works for you!

**Comment by arashberlin** [comment]
Many thanks for the prompt response. I am impressed with your solution and am exploring various use cases for my company. However, I am unable to utilize the widget on our intranet, as it retrieves a response from the endpoint https://api.elevenlabs.io/v1/... and plays back the audio. 

Sadly, we are not allowed to use any proxies in our environment. Your AudioNative player only works on internet (web) applications.

I can employ your API endpoint to send the text and receive the result, or alternatively, prepare the audio in advance and use it with my own custom-developed "widget".

Are you familiar with Make.com? It might be possible to use Make.com to transmit and receive data from your endpoint.

Regards
Arash

**Comment by lharries** [comment]
If you can't load from our URL I think you'd be better using our TTS endpoint and then storing the audio on S3 or another source. Here's a tutorial for you on how to do that: https://elevenlabs.io/docs/api-reference/how-to-use-tts-with-streaming
