### ISSUE TITLE
Twilio call LLM - Enterprise feature only

### ISSUE THREAD

**Issue by teovillanueva** [elevenlabs/elevenlabs-examples#31]
Hello! I've been trying to run the twillio llm call example but it looks like the [line](https://github.com/elevenlabs/elevenlabs-examples/blob/ea93012cd714f4f4fb9a3bee81960a75de694dcf/examples/twilio/call-llm/src/app.ts#L40C5-L40C15) throws an error about this being an enterprise only feature. I've tried talking with the ElevenLabs sales team but they told me that feature doesn't exist and that "speech to text function is actually drawn from Twilio rather than from ElevenLabs". I would appreciate some clarification if possible! Thanks!

**Comment by dev-nidhishbhavsar** [comment]
Having same issue

**Comment by dev-nidhishbhavsar** [comment]
@teovillanueva refer below link for speech to text fix I found
https://github.com/twilio-labs/call-gpt/blob/main/app.js

**Comment by louisjoecodes** [comment]
Thanks @dev-nidhishbhavsar
