### ISSUE TITLE
Twilio Call Voice Dubbing

### ISSUE THREAD

**Issue by shehzadraheem** [elevenlabs/elevenlabs-examples#46]
Actually, I want to build a live voice translated app.
Let suppose client A speaks English and client B speaks German.

When client A makes a voice call to client B, then during a call I want to get client A audio and dubbed that audio file into a German language and then place that audio file into the call again. So that user B listen it in German and vice versa.

How can I do that with Twilio and Elevenlabs?

**Comment by louisjoecodes** [comment]
We don't currently support live-dubbing unfortunately - our Dubbing API is long-running which means you would need to wait for it to finish processing. Apologies for this! Something we are actively working on.
