### ISSUE TITLE
audio_file

### ISSUE THREAD

**Issue by wanglongpeng1** [elevenlabs/elevenlabs-examples#47]
I want to know if I call dubbing_api what to fill in the File format column
我想知道，如果我调用dubbing_api 在File format一栏中填什么
  

  result = create_dub_from_file(
        "",  # Input file path
        "audio/mp3",  # File format
        "en",  # Source language
        "zh",  # Target language
    )

**Comment by louisjoecodes** [comment]
Hello! I hope this guide helps answer this question: https://elevenlabs.io/docs/developer-guides/how-to-dub-a-video

For any specifics please feel free to re-open.
