### ISSUE TITLE
Request for tool agent calling capibilities with realtime conversational ai 

### ISSUE THREAD

**Issue by oussamaJmaaa** [elevenlabs/elevenlabs-examples#62]
Currently, ElevenLabs provides knowledge base support for conversational AI, but it lacks the ability to dynamically execute external API calls during conversations. Adding tool-agent calling capabilities would allow the AI to fetch or process real-time information (e.g., weather, bookings) based on user input, greatly enhancing interaction quality and responsiveness.

Thank you for considering this enhancement—it would expand ElevenLabs' real-time utility and adaptability in conversations.

**Comment by noltondyer** [comment]
Agreed, this is a huge huge feature that we're waiting for.

**Comment by beydogan** [comment]
It already has under "Tools" you can connect APIs.

<img width="780" alt="image" src="https://github.com/user-attachments/assets/e4ba917f-248a-435b-b919-f4a05e275e19">

**Comment by louisjoecodes** [comment]
Hello! We have both client-side & server-side tools now in Conversational AI. There are a few examples in the /conversational-ai folder in this repository.
