### ISSUE TITLE
Feature request: Live transcript feature in frontend for Conversational AI Agent

### ISSUE THREAD

**Issue by agnibha-turing** [elevenlabs/elevenlabs-examples#67]
Can we add a way to show the live transcript in the frontend of the JavaScript Conversational AI Agent? Would be very helpful, thanks, I was trying to figure out a way but would be grateful if a solution already exists!

**Comment by SeloSlav** [comment]
Hey @agnibha-turing, I've been trying to implement the live transcript functionality, but I've encountered some issues. Specifically, I'm not able to retrieve the user_transcript and agent_response from the onMessage callback of the WebSocket as expected.

I tried setting up my callback function to handle the user_transcription_event and agent_response_event, but it seems that the incoming message structure doesn't align with what I anticipated based on the ElevenLabs API documentation. This results in the transcript not being updated in real time.

Here's what I tried:

onMessage: (message) => {
  console.log('Message received:', message);
  if (message.type === 'user_transcript') {
    setTranscript((prevTranscript) => [
      ...prevTranscript,
      { role: 'user', message: message.user_transcription_event.user_transcript },
    ]);
  } else if (message.type === 'agent_response') {
    setTranscript((prevTranscript) => [
      ...prevTranscript,
      { role: 'agent', message: message.agent_response_event.agent_response },
    ]);
  } else {
    console.warn('Unexpected message structure:', message);
  }
},

I suspect there might be something I'm missing about the message formats or perhaps a different approach is needed to receive and parse these events properly. If you or anyone else has managed to get it working, I'd really appreciate any guidance. Thanks!

Linking the API reference here for more context: https://elevenlabs.io/docs/conversational-ai/api-reference/websocket#client-to-server-messages

**Comment by RohilH** [comment]
Also running into this issue, the onMessage handler does not seem to be returning any messages, either from the agent or the human/user

**Comment by louisjoecodes** [comment]
Hello! The onMessage handler should be all you need to store the transcript live.

```
import { useConversation } from "@11labs/react";
...
const conversation = useConversation();
...
conversation.startSession({
        signedUrl, // or agentId if using a public agent
        onMessage: (message) => {
          console.log(message);
        },
...
```


<img width="698" alt="Screenshot 2024-12-08 at 12 40 03" src="https://github.com/user-attachments/assets/4fa5f50d-13b1-4e44-a295-e912c3a24dbb">

**Comment by SeloSlav** [comment]
Hey,

Here's my full code. The transcripts are still not being logged.

``
'use client';

import { useConversation } from '@11labs/react';
import React, { useCallback, useEffect, useRef, useState } from 'react';
import dotenv from 'dotenv';
dotenv.config();

export function ConversationComponent() {
  const [microphoneEnabled, setMicrophoneEnabled] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');
  const [volume, setVolume] = useState(1); // Default volume at 100%
  const [transcript, setTranscript] = useState([]); // State to store transcript lines
  const transcriptRef = useRef(null);

  const conversation = useConversation();

  useEffect(() => {
    if (transcriptRef.current) {
      transcriptRef.current.scrollTop = transcriptRef.current.scrollHeight;
    }
  }, [transcript]);

  const startConversation = useCallback(() => {
    console.log('Requesting microphone access...');
    navigator.mediaDevices.getUserMedia({ audio: true })
      .then(() => {
        console.log('Microphone access granted.');
        setMicrophoneEnabled(true);

        console.log('Starting conversation session...');
        conversation.startSession({
          agentId: 'tRQ8VBuYOhpOecaDuGiX', // Replace with your actual Agent ID
          onMessage: (message) => {
            console.log('Message received:', message);
            setTranscript((prevTranscript) => [
              ...prevTranscript,
              { role: message.source === 'ai' ? 'agent' : 'user', message: message.message },
            ]);
          },
        });

        setTranscript([]); // Clear transcript on starting a new session
      })
      .catch((error) => {
        console.error('Microphone access denied:', error);
        setErrorMessage('Microphone access is required. Please allow microphone access in your browser settings.');
      });
  }, [conversation]);

  const stopConversation = useCallback(() => {
    console.log('Ending conversation session...');
    conversation.endSession();
    setMicrophoneEnabled(false);
  }, [conversation]);

  const adjustVolume = useCallback((event) => {
    const volumeLevel = parseFloat(event.target.value);
    setVolume(volumeLevel);
    conversation.setVolume({ volume: volumeLevel });
  }, [conversation]);

  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-gradient-to-b from-pink-100 via-rose-200 to-amber-100 p-4">
      <div className="max-w-xl w-full bg-white shadow-xl rounded-lg p-6 text-center">

        {!microphoneEnabled && (
          <div className="bg-yellow-100 text-yellow-800 px-4 py-3 rounded mb-4">
            Please enable your microphone to start a conversation.
          </div>
        )}

        {errorMessage && (
          <div className="bg-red-100 text-red-800 px-4 py-3 rounded mb-4">
            {errorMessage}
          </div>
        )}

        <div className="flex gap-4 justify-center mb-4">
          <button
            onClick={startConversation}
            disabled={conversation.status === 'connected'}
            className="px-4 py-2 bg-rose-500 text-white font-semibold rounded-lg hover:bg-rose-600 disabled:bg-gray-300"
          >
            Enable Microphone
          </button>
          <button
            onClick={stopConversation}
            disabled={conversation.status !== 'connected'}
            className="px-4 py-2 bg-gray-500 text-white font-semibold rounded-lg hover:bg-gray-600 disabled:bg-gray-300"
          >
            End Conversation
          </button>
        </div>

        <div className="flex items-center gap-4 mb-4">
          <label htmlFor="volume-slider" className="text-rose-900 font-semibold">Volume:</label>
          <input
            id="volume-slider"
            type="range"
            min="0"
            max="1"
            step="0.1"
            value={volume}
            onChange={adjustVolume}
            className="w-full"
          />
        </div>

        {conversation.status === 'connected' && conversation.isSpeaking && (
          <div className="mb-4">
            <div className="w-8 h-8 rounded-full bg-rose-500 animate-pulse mx-auto"></div>
            <p className="text-rose-900 font-semibold mt-2">Agent is speaking...</p>
          </div>
        )}

        <div className="bg-amber-50 p-4 rounded-lg w-full shadow-inner mb-6">
          <h2 className="text-xl font-semibold text-rose-900 mb-2">Conversation Transcript</h2>
          <div ref={transcriptRef} className="text-left overflow-y-auto max-h-48">
            {transcript.length > 0 ? (
              transcript.map((line, index) => (
                <div key={index} className={`flex ${line.role === 'user' ? 'justify-end' : 'justify-start'} mb-2`}>
                  <div
                    className={`inline-block p-2 rounded-lg ${line.role === 'user' ? 'bg-blue-500 text-white' : 'bg-gray-200 text-gray-800'}`}
                  >
                    {line.message}
                  </div>
                </div>
              ))
            ) : (
              <p className="text-gray-500 italic">No messages yet. Start talking!</p>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
``

**Comment by SeloSlav** [comment]
Hey,

Here's my full code. The transcripts are still not being logged.

```
'use client';

import { useConversation } from '@11labs/react';
import React, { useCallback, useEffect, useRef, useState } from 'react';
import dotenv from 'dotenv';
dotenv.config();

export function ConversationComponent() {
  const [microphoneEnabled, setMicrophoneEnabled] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');
  const [volume, setVolume] = useState(1); // Default volume at 100%
  const [transcript, setTranscript] = useState([]); // State to store transcript lines
  const transcriptRef = useRef(null);

  const conversation = useConversation();

  useEffect(() => {
    if (transcriptRef.current) {
      transcriptRef.current.scrollTop = transcriptRef.current.scrollHeight;
    }
  }, [transcript]);

  const startConversation = useCallback(() => {
    console.log('Requesting microphone access...');
    navigator.mediaDevices.getUserMedia({ audio: true })
      .then(() => {
        console.log('Microphone access granted.');
        setMicrophoneEnabled(true);

        console.log('Starting conversation session...');
        conversation.startSession({
          agentId: '**AGENT_ID_HERE**', // Replace with your actual Agent ID
          onMessage: (message) => {
            console.log('Message received:', message);
            setTranscript((prevTranscript) => [
              ...prevTranscript,
              { role: message.source === 'ai' ? 'agent' : 'user', message: message.message },
            ]);
          },
        });

        setTranscript([]); // Clear transcript on starting a new session
      })
      .catch((error) => {
        console.error('Microphone access denied:', error);
        setErrorMessage('Microphone access is required. Please allow microphone access in your browser settings.');
      });
  }, [conversation]);

  const stopConversation = useCallback(() => {
    console.log('Ending conversation session...');
    conversation.endSession();
    setMicrophoneEnabled(false);
  }, [conversation]);

  const adjustVolume = useCallback((event) => {
    const volumeLevel = parseFloat(event.target.value);
    setVolume(volumeLevel);
    conversation.setVolume({ volume: volumeLevel });
  }, [conversation]);

  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-gradient-to-b from-pink-100 via-rose-200 to-amber-100 p-4">
      <div className="max-w-xl w-full bg-white shadow-xl rounded-lg p-6 text-center">

        {!microphoneEnabled && (
          <div className="bg-yellow-100 text-yellow-800 px-4 py-3 rounded mb-4">
            Please enable your microphone to start a conversation.
          </div>
        )}

        {errorMessage && (
          <div className="bg-red-100 text-red-800 px-4 py-3 rounded mb-4">
            {errorMessage}
          </div>
        )}

        <div className="flex gap-4 justify-center mb-4">
          <button
            onClick={startConversation}
            disabled={conversation.status === 'connected'}
            className="px-4 py-2 bg-rose-500 text-white font-semibold rounded-lg hover:bg-rose-600 disabled:bg-gray-300"
          >
            Enable Microphone
          </button>
          <button
            onClick={stopConversation}
            disabled={conversation.status !== 'connected'}
            className="px-4 py-2 bg-gray-500 text-white font-semibold rounded-lg hover:bg-gray-600 disabled:bg-gray-300"
          >
            End Conversation
          </button>
        </div>

        <div className="flex items-center gap-4 mb-4">
          <label htmlFor="volume-slider" className="text-rose-900 font-semibold">Volume:</label>
          <input
            id="volume-slider"
            type="range"
            min="0"
            max="1"
            step="0.1"
            value={volume}
            onChange={adjustVolume}
            className="w-full"
          />
        </div>

        {conversation.status === 'connected' && conversation.isSpeaking && (
          <div className="mb-4">
            <div className="w-8 h-8 rounded-full bg-rose-500 animate-pulse mx-auto"></div>
            <p className="text-rose-900 font-semibold mt-2">Agent is speaking...</p>
          </div>
        )}

        <div className="bg-amber-50 p-4 rounded-lg w-full shadow-inner mb-6">
          <h2 className="text-xl font-semibold text-rose-900 mb-2">Conversation Transcript</h2>
          <div ref={transcriptRef} className="text-left overflow-y-auto max-h-48">
            {transcript.length > 0 ? (
              transcript.map((line, index) => (
                <div key={index} className={`flex ${line.role === 'user' ? 'justify-end' : 'justify-start'} mb-2`}>
                  <div
                    className={`inline-block p-2 rounded-lg ${line.role === 'user' ? 'bg-blue-500 text-white' : 'bg-gray-200 text-gray-800'}`}
                  >
                    {line.message}
                  </div>
                </div>
              ))
            ) : (
              <p className="text-gray-500 italic">No messages yet. Start talking!</p>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
```
